Hairpin NAT and reflection zone for VPN
NethServer/nethsecurity-docs pull request #117
Opened 2024-09-26 08:24 UTC by cotosso

If a reflection zone for hairpin nat is a vpn you need to specify the subnet.

2024-09-26 09:25 UTC, gsanchietti requested changes
One last note:
are you sure the correct CIDR to use is the network 10.88.88.0/24 and not the first IP of the network 10.88.88.1/24?

2024-09-26 09:25 UTC, gsanchietti commented on port_forward.rst
> +    uci set firewall.ns_49d9f400.subnet=10.88.88.0/24
The subnet field should be always a list
```suggestion
    uci add_list firewall.ns_49d9f400.subnet=10.88.88.0/24
```

2024-09-26 09:25 UTC, gsanchietti commented on port_forward.rst
> +Add or remove multiple subnets to the vpn zone
```suggestion
Add or remove multiple subnets to the VPN zone
```

2024-09-26 09:25 UTC, gsanchietti commented on port_forward.rst
> +Hairpin NAT for VPN Zones
```suggestion
Hairpin NAT for VPN zones
```

2024-09-26 15:36 UTC, cotosso commented on port_forward.rst
> +To use Hairpin NAT with VPN zones such as ipsec, openvpn, and rwopenvpn, additional configuration is necessary.
I intentionally wrote  ipsec, openvpn, rwopenvpn  exactly as they are written in the zone section.

2024-09-26 15:39 UTC, cotosso commented on port_forward.rst
> +To use Hairpin NAT with VPN zones such as ipsec, openvpn, and rwopenvpn, additional configuration is necessary.
About the 10.88.88.1/24 question: i made a test in a real situation and it worked flawlessy using 0 as last octet, even with 2 subnets declared for the same zone.

2024-09-27 04:54 UTC, gsanchietti commented on port_forward.rst
> +To use Hairpin NAT with VPN zones such as ipsec, openvpn, and rwopenvpn, additional configuration is necessary.
```suggestion
To use Hairpin NAT with VPN zones such as `ipsec`, `openvpn`, and `rwopenvpn`, additional configuration is necessary. 
```

2024-09-27 04:55 UTC, gsanchietti commented on port_forward.rst
> +- `rwopenvpn`: OpenVPN Road Warrior
```suggestion
- ``ipsec``: IPsec tunnels
- ``openvpn``: OpenVPN tunnels
- ``rwopenvpn``: OpenVPN Road Warrior
```

2024-09-27 06:38 UTC, gsanchietti approved these changes

2024-09-27 06:39 UTC, merged