subscription: add alerts chapter
NethServer/nethsecurity-docs pull request #22
Opened 2023-12-15 10:33 UTC by gsanchietti

Card: https://trello.com/c/QeMYxNCq/201-release-notes

2023-12-15 12:00 UTC, filippocarletti requested changes

2023-12-15 12:00 UTC, filippocarletti commented on subscription.rst
> +The system will automatically registered to the correct Enterprise or Community portal
```suggestion
The system will automatically register to the correct Enterprise or Community portal
```

2023-12-15 12:00 UTC, filippocarletti commented on metrics.rst
> +If the firewall is connected to the :ref:`remote controller <controller-section>`, metrics will be stored to the controller itself and preserved across reboots.ùù
```suggestion
If the firewall is connected to the :ref:`remote controller <controller-section>`, metrics will be stored to the controller itself and preserved across reboots.
```

2023-12-18 13:09 UTC, cotosso commented on metrics.rst
> +Both ``my.nethesis.it`` and ``my.nethserver.com`` serve as central hubs for receiving alerts, allowing administrators to stay informed about the firewall's
Both ``my.nethesis.it`` and ``my.nethserver.com`` serve as central hubs for receiving alerts, allowing administrators to stay informed about the firewall's status and promptly respond to any critical situations.

2023-12-18 16:59 UTC, merged