Update qos.rst after first UI release
NethServer/nethsecurity-docs pull request #24
Opened 2024-01-26 13:52 UTC by cotosso

Update qos.rst after first UI release
I modified the document thinking of the sysadmin as the recipient, thus removing some interesting but unnecessary technical information while still indicating the instructions for any changes from the console at the end

2024-01-26 14:05 UTC, filippocarletti requested changes

2024-01-26 14:05 UTC, filippocarletti commented on qos.rst
> +While QoS can be set up on any interface, it typically functions optimally on WAN-type interfaces, aligning upload and download data with connectivity parameters.
```suggestion
While QoS can be set up on any interface, it typically functions optimally on WAN-type interfaces, setting upload and download speeds to the internet connection data rates.
```

2024-01-26 14:05 UTC, filippocarletti commented on qos.rst
> +The QoS uses four classes of priority, each class can use a maximum percentage of bandwidth defined by its threshold.
```suggestion
QoS uses four classes of priority, each class can use a maximum percentage of bandwidth defined by its threshold.
```

2024-01-29 07:43 UTC, gsanchietti commented on qos.rst
> +====================
```suggestion
====================


QoS relies on an eBPF (Extended Berkeley Packet Filter) based classifier to set Differentiated Services Code Point (DSCP) fields in packets. This classification helps prioritize and manage network traffic efficiently.
To maximize efficiency, QoS operates in the kernel space using eBPF technology. This ensures minimal overhead and minimal impact on system performance.
In addition to IP and port-based rules, QoS allows you to define traffic rules based on DNS names, providing granular control over how traffic is classified and treated.
```

2024-01-29 07:43 UTC, merged