New UI port and 2FA
NethServer/nethsecurity-docs pull request #37
Opened 2024-02-08 07:21 UTC by gsanchietti

Card: https://trello.com/c/AotUwjir/317-new-ui-port

2024-02-08 09:08 UTC, filippocarletti requested changes

2024-02-08 09:08 UTC, filippocarletti commented on remote_access.rst
> +- remove the ``Allow-UI-from-WAN`` rule: go to the Firewall rules page,  navigate to the ``Input rules`` tab,
```suggestion
- remove the ``Allow-UI-from-WAN`` rule: go to the Firewall rules page, navigate to the ``Input rules`` tab,
```

2024-02-08 09:08 UTC, filippocarletti commented on remote_access.rst
> +To mitigate this risk, you can take two main steps:
```suggestion
To mitigate this risk, you have two options (remove or restrict access):
```

2024-02-08 09:08 UTC, filippocarletti commented on remote_access.rst
> +- allowing access from specific IPs or networks: in the Firewall rules page, locate the "Allow-UI-from-WAN"
```suggestion
- restrict access from specific IPs or networks: in the Firewall rules page, locate the "Allow-UI-from-WAN"
```

2024-02-08 09:08 UTC, filippocarletti commented on remote_access.rst
> +  For example, to allow access only from your home network, you could enter the IP range 192.168.1.0/24
```suggestion
  For example, to allow access only from your home network, you could enter the 192.168.1.0/24 network.
```

2024-02-08 09:08 UTC, filippocarletti commented on remote_access.rst
> +To change NethSecurity UI port from 9090 to 8181, execute: ::
```suggestion
To change the NethSecurity UI port from 9090 to 8181, execute: ::
```

2024-02-08 09:08 UTC, filippocarletti commented on remote_access.rst
> +may introduces a potential security risk. Here's how to safely maintain port 443 functionality while protecting your NethSecurity UI.
```suggestion
may introduce a potential security risk. Here's how to safely maintain port 443 functionality while protecting your NethSecurity UI.
```

2024-02-08 09:08 UTC, filippocarletti commented on remote_access.rst
> +Execute the following command on your NethServer system: ::
```suggestion
Execute the following commands on your NethServer system: ::
```

2024-02-08 10:00 UTC, filippocarletti approved these changes

2024-02-09 16:38 UTC, cotosso approved these changes
Everything seems fine to me!

2024-02-09 16:52 UTC, merged