threat shield: describe new page
NethServer/nethsecurity-docs pull request #47
Opened 2024-02-15 16:33 UTC by gsanchietti

Card: https://trello.com/c/UbzjFAwP/314-threat-shield-ip-minimal-ui

2024-02-15 16:45 UTC, filippocarletti requested changes

2024-02-15 16:45 UTC, filippocarletti commented on threat_shield.rst
> +The service can load community blocklist or can relay on high quality blocklists very frequently updated and maintained by `Yoroy <https://yoroi.company>`_ a leading company focused on
```suggestion
The service can load community blocklists or can rely on high-quality blocklists very frequently updated and maintained by `Yoroy <https://yoroi.company>`_ a leading company focused on
```

2024-02-15 16:50 UTC, filippocarletti approved these changes

2024-02-16 14:50 UTC, cotosso approved these changes

2024-02-16 15:16 UTC, merged

2024-02-16 15:18 UTC, filippocarletti requested changes

2024-02-16 15:18 UTC, filippocarletti commented on threat_shield.rst
>  One of these tools is Threat Shield: a shield that blocks any traffic coming from compromised IP addresses or destined to them as well as any requests addressed to hostnames that could be malicious.
```suggestion
One of these tools is Threat Shield, which blocks any traffic coming from compromised IP addresses or destined to them as well as any requests addressed to hostnames that could be malicious.
```

2024-02-16 15:18 UTC, filippocarletti commented on threat_shield.rst
> +- Fully qualified host name: example.com
```suggestion
- Fully qualified hostname: example.com
```

2024-02-16 15:18 UTC, filippocarletti commented on threat_shield.rst
> +The address can be a valid IPv4/IPv6 address with optional CIDR notation, a MAC address , or a fully qualified host name (FQDN).
```suggestion
The address can be a valid IPv4/IPv6 address with optional CIDR notation, a MAC address, or a fully qualified hostname (FQDN).
```

2024-02-16 15:18 UTC, filippocarletti commented on threat_shield.rst
> +AdBlock can be configured from command line interface as explained in the `developer manual <https://dev.nethsecurity.org/packages/ns-threat_shield/#ts-dns>`_.
```suggestion
AdBlock can be configured from the command line interface as explained in the `developer manual <https://dev.nethsecurity.org/packages/ns-threat_shield/#ts-dns>`_.
```

2024-02-16 15:18 UTC, filippocarletti commented on threat_shield.rst
> +This can help in organizing and managing the allow list effectively.
```suggestion
This can help in organizing and managing the allowlist effectively.
```

2024-02-16 15:18 UTC, filippocarletti commented on threat_shield.rst
> +The DNS filter uses AdBlock that blocks any request to a domain that is considered malicious.
```suggestion
The DNS filter uses AdBlock which blocks any request to a domain that is considered malicious.
```

2024-02-16 15:18 UTC, filippocarletti commented on threat_shield.rst
> +The service can load community blocklists or can rely on high-quality blocklists very frequently updated and maintained by `Nethesis <https://www.nethesis.it>`_ and `Yoroy <https://yoroi.company>`_
```suggestion
The service can load community-maintained blocklists or can rely on high-quality blocklists very frequently updated and maintained by `Nethesis <https://www.nethesis.it>`_ and `Yoroy <https://yoroi.company>`_
```

2024-02-16 15:18 UTC, filippocarletti commented on threat_shield.rst
> +The service can load community blocklist or use Yoroi feeds.
```suggestion
The service can load community-maintained blocklists or use Yoroi feeds.
```