controller: new release (draft)
NethServer/nethsecurity-docs pull request #56
Opened 2024-03-22 13:36 UTC by gsanchietti

New controller

2024-03-26 14:13 UTC, filippocarletti requested changes

2024-03-26 14:13 UTC, filippocarletti commented on controller.rst
> +The controller enables to manage multiple NethSecurity installations remotely, called units.
```suggestion
The controller allows remote control of multiple NethSecurity installations, called units.
```

2024-03-26 14:13 UTC, filippocarletti commented on controller.rst
> +This allows for secure communication between the controller and the unit.
```suggestion
The VPN enables secure communication between the controller and the unit.
```

2024-03-26 14:13 UTC, filippocarletti commented on controller.rst
> +After the configuration is done, the controller is ready to be used and can be accessed using a web browser at the configured hostname, like ``https://mycontroller.nethsecurity.org``.
```suggestion
After completing the configuration, the controller is ready to be used and can be accessed using a web browser at the configured hostname, like ``https://mycontroller.nethsecurity.org``.
```

2024-03-26 14:13 UTC, filippocarletti commented on controller.rst
> +The administrator user is the only one who can create and manage users within the controller.
Repeated from above: remove?

2024-03-26 14:35 UTC, gsanchietti commented on controller.rst
> +The administrator user is the only one who can create and manage users within the controller.
```suggestion
```

2024-03-26 14:35 UTC, gsanchietti commented on controller.rst
> +The administrator user is the only one who can create and manage users within the controller.
Removed

2024-03-27 09:50 UTC, filippocarletti approved these changes

2024-03-27 09:51 UTC, merged