Firewall objects
NethServer/nethsecurity-docs pull request #96
Opened 2024-07-05 10:44 UTC by gsanchietti

NethServer/nethsecurity#567

2024-07-08 09:45 UTC, cotosso commented on objects.rst
> +
```suggestion

.. note::

Host sets are fully supported in their expressive completeness (IP, CIDR, range, groupings) within firewall rules. Other panels might only support a reduced subset (for example, MultiWAN only supports single IP addresses and CIDR). In such cases, only compatible host sets will be displayed.
  
```

2024-07-08 11:05 UTC, filippocarletti requested changes

2024-07-08 11:05 UTC, filippocarletti commented on objects.rst
> +- simplifies management of rules based on web addresses
```suggestion
- simplify management of rules based on web addresses
```

2024-07-08 11:05 UTC, filippocarletti commented on objects.rst
> +- automatically handles IP address changes of websites
```suggestion
- automatically handle IP address changes of websites
```

2024-07-08 11:05 UTC, filippocarletti commented on objects.rst
> +- reduces the need for manual updates to firewall rules
```suggestion
- reduce the need for manual updates to firewall rules
```

2024-07-08 11:05 UTC, filippocarletti commented on objects.rst
> +- provides a more intuitive way to control access to web-based services
```suggestion
- provide a more intuitive way to control access to web-based services
```

2024-07-08 11:05 UTC, filippocarletti commented on objects.rst
> +   - Choose a name that clearly identifies the purpose or group of domains
```suggestion
   - Choose a name that clearly identifies the purpose of the group of domains
```

2024-07-08 12:13 UTC, gsanchietti commented on objects.rst
> +   - In the ``Records`` field, you can add the hosts for this set
Not sure about this

2024-07-08 12:40 UTC, filippocarletti commented on objects.rst
> +   - In the ``Records`` field, you can add the hosts for this set
What about "to"?

2024-07-08 15:05 UTC, gsanchietti commented on objects.rst
> +   - In the ``Records`` field, you can add the hosts for this set
Yes, maybe "to" is better. But I still prefer the original form

2024-07-08 15:26 UTC, filippocarletti commented on objects.rst
> +   - In the ``Records`` field, you can add the hosts for this set
Let's go with "for", then.

2024-07-09 07:07 UTC, gsanchietti commented on objects.rst
> +   - In the ``Records`` field, you can add the hosts for this set
:ok:

2024-07-09 07:27 UTC, gsanchietti commented on objects.rst
> +   - In the ``Records`` field, you can add the hosts for this set
Fixed.

2024-07-15 09:51 UTC, merged